const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

/** How long a signed-in session should last without signing in again. */
export const AUTH_SESSION_DURATION_DAYS = 30;

export const AUTH_SESSION_DURATION_SECONDS =
  AUTH_SESSION_DURATION_DAYS *
  HOURS_PER_DAY *
  MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE;

export const AUTH_SESSION_DURATION_MS =
  AUTH_SESSION_DURATION_SECONDS * MILLISECONDS_PER_SECOND;
